### ISSUE TITLE
Server disconnected error using rpi4

### ISSUE THREAD

**Issue by adriano1501** [jlesage/docker-firefox#67]
hello,
I've installed the container on a rpi4. The container runs fine and I can reach it from the web ui.
Unfortunately I cannot use it because I see error "Server disconnected code 1006".
Looking at the log folder I found two subfolders: firefox and nginx.
In the firefox folder I see an empty file called error.log.
In the nginx folder I see two files: access.log and error.log. In the first file I see the traces of my access attempts and in the second file I see trace like:

`2020/09/21 16:40:21 [alert] 2778#2778: prctl(PR_SET_DUMPABLE) failed (22: Invalid argument)
2020/09/21 16:40:21 [emerg] 2778#2778: io_setup() failed (38: Function not implemented)
2020/09/21 16:40:21 [alert] 2779#2779: prctl(PR_SET_DUMPABLE) failed (22: Invalid argument)
2020/09/21 16:40:21 [emerg] 2779#2779: io_setup() failed (38: Function not implemented)
2020/09/21 16:41:09 [error] 2779#2779: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.27, server: , request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:5900/websockify", host: "192.168.1.53:5800"
2020/09/21 16:41:10 [error] 2779#2779: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.27, server: , request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:5900/websockify", host: "192.168.1.53:5800"
2020/09/21 16:41:11 [error] 2779#2779: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.1.27, server: , request: "GET /websockify HTTP/1.1", upstream: "http://127.0.0.1:5900/websockify", host: "192.168.1.53:5800"
2020/09/21 16:41:39 [emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use)
2020/09/21 16:41:39 [emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use)
2020/09/21 16:41:39 [emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use)
2020/09/21 16:41:39 [emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use)
2020/09/21 16:41:39 [emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use)
2020/09/21 16:41:39 [emerg] 5252#5252: still could not bind()`

Can you please help in having the container working?

Thanks!

**Comment by jlesage** [comment]
`Server disconnected code 1006` is usually fixed by clearing the cache of the browser you are using to access the container.  You can also try with another browser or try with an "incognito" window.

**Comment by adriano1501** [comment]
Hello Jocelyn,many thanks for the reply. I tried to clear out the browser cache and also I tried different browsers but I am still having the same issue. Please let me know if I can provide any log/info that can be useful. Thanks,Adriano Inviato da Posta per Windows 10 Da: Jocelyn Le SageInviato: mercoledì 23 settembre 2020 14:44A: jlesage/docker-firefoxCc: adriano1501; AuthorOggetto: Re: [jlesage/docker-firefox] Server disconnected error using rpi4 (#67) Server disconnected code 1006 is usually fixed by clearing the cache of the browser you are using to access the container. You can also try with another browser or try with an "incognito" window.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jlesage** [comment]
I justesse in your logs that you have:
```
[emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use) 2020/09/21 16:41:39
```

It seems that you already have something running on port 5800.  You probably want to map this port on a different port on the host using the `-p` argument of the `docker run` command.

**Comment by adriano1501** [comment]
Hello Jocelyn,I did further check and I am sure no other process are listening on port 5800.So it looks like the issue is different.Any idea? Thanks,Adriano Inviato da Posta per Windows 10 Da: Jocelyn Le SageInviato: mercoledì 23 settembre 2020 16:23A: jlesage/docker-firefoxCc: adriano1501; AuthorOggetto: Re: [jlesage/docker-firefox] Server disconnected error using rpi4 (#67) I justesse in your logs that you have:[emerg] 5252#5252: bind() to 0.0.0.0:5800 failed (98: Address in use) 2020/09/21 16:41:39It seems that you already have something running on port 5800. You probably want to map this port on a different port on the host using the -p argument of the docker run command.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jlesage** [comment]
According to the logs this is the problem...
Did you check by running  `sudo lsof -i -P -n` on the host ?

**Comment by adriano1501** [comment]
Yes of course.Below the output with docker Firefox running and after I stop it.  As you can see only docker Firefox is listening on the 5800. Inviato da Posta per Windows 10 Da: Jocelyn Le SageInviato: giovedì 24 settembre 2020 14:55A: jlesage/docker-firefoxCc: adriano1501; AuthorOggetto: Re: [jlesage/docker-firefox] Server disconnected error using rpi4 (#67) According to the logs this is the problem...Did you check by running sudo lsof -i -P -n on the host ?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jlesage** [comment]
Sorry I don't see the output you are taking about...
Is it possible that you have 2 instances of the container ?

**Comment by adriano1501** [comment]
Hello Jocelyn,
I'll try to attach the screenshot.
Nope I am running only a single instance of the container.

Thanks,
Adriano

Il mar 29 set 2020, 19:32 Jocelyn Le Sage <notifications@github.com> ha
scritto:
